name: Test release cleanup

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: List releases to delete
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          keep=10

          gh release list \
            --limit 1000 \
            --json tagName,createdAt \
            -q ".[${keep}:] | .[].tagName"
